baseURL = "https://peter-amerkhanian.com"
title = "Peter Amerkhanian"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
canonifyURLs = true
enableEmoji = true
googleAnalytics = "G-V95HGLKTEB"
enableRobotsTXT = true
copyright = "&copy; 2023, Peter Amerkhanian"


# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    title = "Blog"
    url = "/post/"
    weight = -100

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 3
    endLevel = 5
    ordered = true
  
# Configuration Features
[params]
  description = "Portfolio and personal website"      # Your meta description of the site
  header_title = "Peter Amerkhanian"                 # Your header title
  header_subtitle_one = "Data Scientist @ CA Department of Social Services" # Your header subtitle
  header_subtitle_two = "UC Berkeley MPP '23, BA '16" # Your header subtitle
  home_image = "/images/Peter_Amerkhanian_Headshot_square_lower_qual.jpg"          # Path to header image starting from the static directory
  blog_image = "/images/blog.jpg"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"] 
    # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#FFF9EB" #"#F9FEFF"
    fontColor = "#212529"
    fontFamilyBase = "Arial"  
  [[params.social]]
    fa_icon = "fas fa-at fa-lg"
    href = "mailto:peteramerkhanian@berkeley.edu"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-lg"
    href = "https://www.linkedin.com/in/peteramerkhanian/"
  [[params.social]]
    fa_icon = "fab fa-github fa-lg"          # Font Awesome icon class
    href = "https://github.com/peter-amerkhanian"      # Link to associate with icon (http://, https://, mailto:)

