baseURL = "https://example.com"
title = "Your Website Title"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; 2022, Peter Amerkhanian"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    title = "Blog"
    url = "/post/"
    weight = -100

# Configuration Features
[params]
  description = "Portfolio and personal website"      # Your meta description of the site
  header_title = "Peter Amerkhanian"                 # Your header title
  header_subtitle = "MPP '23 @ UC Berkeley Goldman School" # Your header subtitle
  home_image = "/images/Peter_Amerkhanian_Headshot_square_lower_qual.jpg"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fas fa-at fa-lg"
    href = "mailto:peteramerkhanian@berkeley.edu"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-lg"
    href = "https://www.linkedin.com/in/peteramerkhanian/"
  [[params.social]]
    fa_icon = "fab fa-github fa-lg"          # Font Awesome icon class
    href = "https://github.com/peter-amerkhanian"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fas fa-file-alt fa-lg"
    href = ""