---
title: "CLT"
author: "Peter Amerkhanian"
date: "8/23/2022"
draft: true
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Central Limit Theorem

```{r, warning=FALSE, message = FALSE, results='hide'}
library(reshape2)
library(tidyverse)
library(boot)
library(knitr)
```


```{r}
data <- tips
summary(data)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
hist(data$tip, freq=FALSE)
```

```{r}
results <- data.frame()
  
results[1,1] <- "1"
results[1,2] <-  mean(slice_sample(data, n=100, replace=TRUE)$tip)

results[2,1] <- "2"
results[2,2] <-  mean(slice_sample(data, n=100, replace=TRUE)$tip)

results[3,1] <- "3"
results[3,2] <-  mean(slice_sample(data, n=100, replace=TRUE)$tip)

colnames(results) <- c("Sample #", "Sample Mean")

results
```


```{r}
set.seed(3)
```

```{r}
sample_means_100 = vector()
for (i in 1:100) {
  sample_means_100[i] <- mean(slice_sample(data, prop=1, replace=TRUE)$tip)
}
```

```{r}
hist(sample_means_100, freq=FALSE)
```

```{r, cache=TRUE}
sample_means_1000 = vector()
for (i in 1:1000) {
  sample_means_1000[i] <- mean(slice_sample(data, prop=1, replace=TRUE)$tip)
}
```

```{r}
hist(sample_means_1000, freq=FALSE)
```

```{r}

bootstrap_func <- function(data_, i){
 return(mean(data_[i, ]$tip))
}
```


```{r, , cache=TRUE}
paste("For Loop")
sample_means_1000 = vector()
system.time(
  for (i in 1:1000) {
  sample_means_1000[i] <- mean(slice_sample(data, prop=1, replace=TRUE)$tip)
}
)
paste("Function (from `boot`)")
system.time(
  sample_means_boot <- boot(data,bootstrap_func,R=1000)
  )
```
```{r, cache=TRUE}
sample_means_boot <- boot(data,bootstrap_func,R=100000)
```


```{r}
sample_means_1000000 <- sample_means_boot$t
hist(sample_means_1000000)
```
```{r}
(max(sample_means_1000000) - mean(sample_means_1000000)) / sd(sample_means_1000000)
(min(sample_means_1000000) - mean(sample_means_1000000)) / sd(sample_means_1000000)
```

